server:
  port: 8082
  servlet:
    context-path: /vehicle-service

spring:
  application:
    name: vehicle-service

  datasource:
    url: jdbc:mysql://localhost:3306/vehicledb
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: ashraf2305

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true

  cloud:
    config:
      enabled: false

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    fetch-registry: true
    register-with-eureka: true
  instance:
    prefer-ip-address: true

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always

logging:
  level:
    com.vehiclebooking.vehicleservice: DEBUG